### PR TITLE
Add init subcommand

### PR DESCRIPTION
**Pull request by JTS22**
This adds an init-subcommand that is launched as a seperate process at the end of create. When the container is created, the runh create process exits and the init-process is reparented to the nearest subreaper (e. g. a containerd-shim). This PR also changes the internal oci-spec representation to use the oci-spec crate which also works with standard oci images that could not be parsed before.

### CODE REVIEW

**Comment by stlankes** [comment]
bors try

**Comment by stlankes** [comment]
bors retry

**Comment by stlankes** [comment]
bors retry

**Comment by stlankes** [comment]
@JTS22 Can you revise the code to pass the format check. Just call `cargo fmt` and check the results.

**Comment by stlankes** [comment]
bors try

**Comment by JTS22** [comment]
> @JTS22 Can you revise the code to pass the format check. Just call `cargo fmt` and check the results.

I did that and pushed another two commits to my repo but for some reason it does not count as a fork of this repo anymore (maybe due to the visibility change?), so the changes are not showing up here. Guess I will re-fork and create a new PR...

**Comment by stlankes** [comment]
Yes, this could be problem. I close this one and we work on #3.

**Pull request closed without merging**
