### PR TITLE
Change to oci-spec crate

### PR DESCRIPTION
**Pull request by JTS22**
Duplicate of #2 with a new fork. Now also includes the reworked spec command and formatting changes.

### CODE REVIEW

**Comment by JTS22** [comment]
bors try

**Comment by stlankes** [comment]
bors try

**Comment by stlankes** [comment]
Bors is not working. I have to check the configuration.

It isn't necessary to create a new PR. You have only to update your branch `JTS22:main`

**Comment by stlankes** [comment]
bors retry

**Comment by stlankes** [comment]
bors cancel

**Comment by stlankes** [comment]
bors try

**Comment by stlankes** [comment]
bors try-

**Comment by stlankes** [comment]
bors try

**Comment by stlankes** [comment]
Ok, bors is now working. @JTS22 Please take a look on its results.

Currently, you start an init process within a cgroup and not in the namespace. What is the init process doing? The same staff, what the spawned process is doing in start?

**Comment by stlankes** [comment]
bors try

**Review by stlankes — APPROVED** [review]
bors r+

**Pull request merged**
